#  Copyright (C) 2020 Shan Chunqing<vxst@vxst.org>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Generated by Django 2.2.6 on 2019-11-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_hash', models.CharField(max_length=240)),
                ('project_path', models.CharField(max_length=240)),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('is_pending', models.BooleanField(db_index=True)),
                ('stdout_result', models.TextField(max_length=65536)),
            ],
        ),
    ]
